### ISSUE TITLE
[IOS] IOS deployment

### ISSUE THREAD

**Issue by ducmaxime** [papyros/qml-material#354] opened 2016-01-06 08:58 UTC
Hello, I try to use qml-material on IOS emulator. 

I Have this error :

![screen shot 2016-01-06 at 10 21 19](https://cloud.githubusercontent.com/assets/6499846/12139244/60c11a6e-b45f-11e5-86d9-7ab7763b6e4b.png)

Any Idea ?

Thank you

**Comment by marco-piccolino** [comment] 2016-01-07 08:44
seems a duplicate of #351. if so, please close this one. thanks!

**Comment by iBelieve** [comment] 2016-03-31 21:22
Closing to due lack of response from OP. Please reopen if this is still an issue and not a duplicate of #351 .

**Closed by iBelieve** 2016-03-31 21:22 UTC
Labels: question
