### ISSUE TITLE
Material.ListItems can't release the focus when I release the touch on Android

### ISSUE THREAD

**Issue by shaoxie1986** [papyros/qml-material#343] opened 2015-12-22 11:15 UTC
The problem is : when I build an app on android using "Material.ListItems"(example:ListItems.Standard),it focused when I touch the ListItem, but when I release it,the focus always exist,it can't release.
My code is:
import QtQuick 2.5
import Material 0.1
import Material.ListItems 0.1 as ListItems
//import QtQuick.Layouts 1.1

ApplicationWindow {
    visible: true
    title: "Application Name"
    width: 320
    height: 640

    Sidebar {
        id: sideBar
        //        width: Units.dp(320)
        expanded: false
        ListItems.Standard {
//            focus: false
            width: sideBar.width
            text: "React Play"
            action: AwesomeIcon {
                name: "clock_o"
                anchors.verticalCenter: parent.verticalCenter

            }
            onClicked: {
                rootPage.x = 0
                sideBar.expanded = false
            }
        }
    }

    initialPage: Page {

        title: "File Server"
        id: rootPage
        backAction: Action {
            iconName: "awesome/navicon"
            onTriggered: {
                rootPage.x = sideBar.width
                sideBar.expanded = true
            }
        }

        Flickable {
            anchors.fill: parent
            contentHeight: Math.max(rootPage.implicitHeight, height)
            Column{
                id: content
                //                anchors.top: parent.top
                //                anchors.left: parent.left
                width: rootPage.width
                //                width: rootPage.width
                ListItems.Subheader {
                    text: "Local"
                }
                ListItems.Standard {
                    text: "My Files"
//                    focus: false
                    //                valueText: "fuck"
                    action: AwesomeIcon {
                        name: "file_o"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                    secondaryItem: AwesomeIcon {
                        name: "angle_right"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                }

                ListItems.Standard {
                    text: "React Play"
//                    focus: false
                    action: AwesomeIcon {
                        name: "clock_o"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                    secondaryItem: AwesomeIcon {
                        name: "angle_right"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                }
                ListItems.Standard {
//                    focus: false
                    text: "Album Media"
                    action: AwesomeIcon {
                        name: "youtube_play"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                    secondaryItem: AwesomeIcon {
                        name: "angle_right"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                }

                ListItems.Divider {

                }

                ListItems.Subheader {
                    text: "Remote"
                }

                ListItems.Standard {
//                    focus: false
                    text: "Play Net Movie"
                    action: AwesomeIcon {
                        name: "cloud"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                    secondaryItem: AwesomeIcon {
                        name: "angle_right"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                }

                ListItems.Divider {

                }

                ListItems.Subheader {
                    text: "Wifi Trans"
                }

                ListItems.Standard {
                    text: "Wifi Trans"
//                    focus: true
//                    activeFocus: false
                    //                iconName: "file/cloud"
                    action: AwesomeIcon {
                        name: "wifi"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                    secondaryItem: AwesomeIcon {
                        name: "angle_right"
                        anchors.verticalCenter: parent.verticalCenter
                    }
                }
                Button {
                    text: "button"
                    elevation: 1
                }
            }
        }
    }
}

is my code wrong?
I am chinese,english is a little weak,wish you can read it.

**Comment by marco-piccolino** [comment] 2015-12-22 11:24
is this a duplicate of #321?

**Comment by shaoxie1986** [comment] 2015-12-22 11:34
thank you @marco-piccolino

**Comment by iBeliever** [comment] 2016-01-06 18:07
Closing as a duplicate of #321.

**Closed by iBeliever** 2016-01-06 18:07 UTC
