### ISSUE TITLE
 font is too small on pc computer

### ISSUE THREAD

**Issue by kikop11** [papyros/qml-material#333] opened 2015-11-10 00:56 UTC
Run on a PC desktop computer, interface font is too small, how to overall adjustment? 
Where to modify QML

**Comment by CircumnavigationJourney** [comment] 2015-11-22 18:22
The expensive way to do it is to use  Component.onCompleted: Units.multiplier = X in your app window, where X is some value > 1.4 (try 2 or 2.5)

You can go to Units class and change the default value (property real multiplier: 1.4 //default multiplier, but can be changed by user).
And to be able to use multiplier you have to set proportions values like for example "width: Units.dp(someValue)"

**Comment by iBeliever** [comment] 2016-01-16 18:12
Duplicate of #230.

**Closed by iBeliever** 2016-01-16 18:12 UTC
